name: Build MCC

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PROJECT: "MinecraftClient"
  TARGET_VERSION: "net10.0"
  DOTNET_VERSION: "10.0.x"
  COMPILE_FLAGS: "--self-contained=true -c Release -p:UseAppHost=true -p:IncludeNativeLibrariesForSelfExtract=true -p:EnableCompressionInSingleFile=true -p:DebugType=Embedded -p:PublishSingleFile=true"

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        target:
          - win-x86
          - win-x64
          - win-arm64
          - linux-x64
          - linux-arm
          - linux-arm64
          - osx-x64
          - osx-arm64

    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: |
          dotnet publish \
            "${{ github.workspace }}/${{ env.PROJECT }}/${{ env.PROJECT }}.csproj" \
            -f "${{ env.TARGET_VERSION }}" \
            -r "${{ matrix.target }}" \
            ${{ env.COMPILE_FLAGS }}
        env:
          DOTNET_NOLOGO: true

      - name: Rename Binary
        shell: bash
        run: |
          if [[ "${{ matrix.target }}" == win-* ]]; then
            EXT=".exe"
          else
            EXT=""
          fi

          SOURCE="${{ github.workspace }}/${{ env.PROJECT }}/bin/Release/${{ env.TARGET_VERSION }}/${{ matrix.target }}/publish/${{ env.PROJECT }}${EXT}"
          OUTPUT="${{ env.PROJECT }}-${{ matrix.target }}${EXT}"

          mv "$SOURCE" "$OUTPUT"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT }}-${{ matrix.target }}
          path: ${{ env.PROJECT }}-${{ matrix.target }}${{ (startsWith(matrix.target, 'win') && '.exe') || '' }}
          if-no-files-found: error
          retention-days: 30
